#!/bin/bash

# setup Tank Repeater mechanism
# NMEA2000 tank senders that report multiple tanks appear as a single tank in VenusOS
# and ends up being displayed as a constantly changing set of values (one set for each tank)
# The Tank Repeater splits the incoming tank into separate dBus services
# and hides the original, producing stable display
#
# When running from the command line this script asks the user a serise of questions about
# what needs to be done
#
# This script makes use of SetupHelper, a separate package to streamline code in this script
# and automate reinstallation following a Venus software update which overwrites the modifications
# made here. SetupHelper must be installed before running this script.

# Venus files that need to be updated to activeate this package
qmlDir=/opt/victronenergy/gui/qml
overviewMobileFile="$qmlDir/OverviewMobile.qml"
reasonMessageFile="$qmlDir/SystemReasonMessage.qml"

# log file for this package (if any)
# leave null ("") if there isn't one
packageLogFile="/var/log/TankRepeater/current"

actionText=""

#### following lines incorporate SetupHelper utilities into this script
# Refer to the SetupHelper ReadMe file for details.
    
source "/data/SetupHelper/CommonResources"

if [ $scriptAction == 'EXIT' ] ; then
    exit
fi

checkFileSets

#### end of lines to include SetupHelper

#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
    echo
    echo "The Tank Repeater provides a stable display for"
    echo "NMEA2000 tank systems that report multiple tanks"

    standardActionPrompt
fi

#### here to do the actual work

if [ $scriptAction == 'INSTALL' ] ; then
    logMessage "++ Installing repeater"

    updateActiveFile "$overviewMobileFile"

    service="/service/TankRepeater"
    if [ ! -e "$service" ]; then
        logMessage "starting repeater service"
        ln -s $scriptDir/service "$service"
    elif ! $runningAtBoot; then
        logMessage "restarting repeater service"
        svc -t "$service"
    fi
    if $filesUpdated ; then
        restartGui=true
    fi
fi

# #### uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
    logMessage "++ Uninstalling repeater"

    # remove and stop repeater service
    # exclude process names that include this script's PID ($$)
    # so this startup script isn't killed in the process!
    if [ -e /service/TankRepeater ]; then
        logMessage "removing repeater service"
        rm -rf /service/TankRepeater
        ps -l | grep TankRepeater | grep -v -e grep -e $$  | awk '{print $3}' | xargs kill > /dev/null 2>&1
    fi

    dBusService="/Settings/Devices/TankRepeater/IncomingTankService"
    serviceName=$(dbus -y com.victronenergy.settings "$dBusService" GetValue)
    if [ $serviceName != "''" ] ; then
        logMessage unhiding original Tank dBus service
        dbus -y com.victronenergy.settings "$dBusService" SetValue "" > /dev/null 2>&1
        restartGui=true
    fi

    restoreActiveFile "$overviewMobileFile"
fi

if $filesUpdated ; then
    restartGui=true
fi

# thats all folks - SCRIPT EXITS INSIDE THE FUNCTION
endScript


